### ISSUE TITLE
Does not fail gracefully with insufficient privileges

### ISSUE THREAD

**Issue by NickMcAvoy** [kflu/serman#3]
An attempt to install with insufficient privileges fails but still leads to the creation of executable etc in `C:\serman\services`

```
$>serman install %cd%\relay.xml IdcpEnvironment=dev
Executing c:\serman\services\relay\relay.exe install...
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at WMI.Win32ServicesProxy.Create(String , String , String , ServiceType , ErrorControl , StartMode , Boolean , String , String , String[] )
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
Executing c:\serman\services\relay\relay.exe start...
WMI.WmiException: NoSuchService
   at winsw.WrapperService.ThrowNoSuchService()
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```

**Comment by kflu** [comment]
There're different steps requiring different kinds of permissions (write to file, install service, setting global environment vars,...). So it would be hard to check if the current process is sufficiently elevated. 

The other way of doing this is to revert back when something failed. But at the moment maybe just run `uninstall` ?
