### ISSUE TITLE
Consider `serman install` to overwrite the existing executable

### ISSUE THREAD

**Issue by NickMcAvoy** [kflu/serman#4]
Running `serman install` after a failed attempt to install the service fails because the executable already exists:

```
Unhandled Exception: System.IO.IOException: The file 'c:\serman\services\relay\relay.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at serman.Program.DeployWrapper(Context ctx)
   at serman.Program.<>c.<Main>b__0_0(InstallOpts opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at serman.Program.Main(String[] args)
```

The directory must by manually removed in order to try again.

**Comment by kflu** [comment]
a new parameter `--overwrite` is introduced for this purpose.
